#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = test
APP_NAME = test
test_APPLICATION_ICON = 


#
# Libraries
#
test_LIBRARIES_DEPEND_UPON += -lNGObjWeb 

#
# Resource files
#
test_RESOURCE_FILES = \
Resources/test.gorm \
Resources/Main.gsmarkup \
Resources/MainMenu-GNUstep.gsmarkup \
Resources/MainMenu-OSX.gsmarkup 


#
# Header files
#
test_HEADER_FILES = \
AppController.h

#
# Class files
#
test_OBJC_FILES = \
AppController.m \
Text.m \
Table.m \
Window.m \
Button.m

#
# Other sources
#
test_OBJC_FILES += \
test_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
